# Generated by Django 5.2.1 on 2025-05-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoutes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='born',
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qoutes_app.author')),
                ('tags', models.ManyToManyField(to='qoutes_app.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
